name: ecom_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.0.5
  flutter_signin_button: ^1.0.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  legacy_progress_dialog: ^0.1.2
  cloud_firestore: ^3.1.8
  location: ^4.3.0
  google_sign_in: ^5.2.4
  email_validator: ^2.0.1
  open_mail_app: ^0.4.4
  geocoding: ^2.0.2
  csc_picker: ^0.2.6
  flutter_neumorphic: ^3.2.0
  animated_text_kit: ^4.2.1
  provider: ^6.0.2
  image_picker: ^0.8.4+10
  firebase_storage: ^10.2.9
  galleryimage: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Bold.ttf
        - asset: fonts/Lato-Regular.ttf
          weight: 700